### ISSUE TITLE
snowc has a problem - The error was: Click to see exception details.

### ISSUE THREAD

**Issue by panthersdude2001** [panthersdude2001/UTimer#7]
The user snowc on computer BRYCE-PC, has encountered an error when using the program. The following details follows.
System.NotImplementedException: The method or operation is not implemented.
   at WCT_Timer.MainFormLAG.FrmLAG_Load(Object sender, EventArgs e) in C:\Users\snowc\Source\Repos\WCT-Timer\WDLCT 3.5\Wildcat All-In-One Timer\MainFormLAG.vb:line 151
   at System.EventHandler.Invoke(Object sender, EventArgs e)
   at System.Windows.Forms.Form.OnLoad(EventArgs e)
   at System.Windows.Forms.Form.OnCreateControl()
   at System.Windows.Forms.Control.CreateControl(Boolean fIgnoreVisible)
   at System.Windows.Forms.Control.CreateControl()
   at System.Windows.Forms.Control.WmShowWindow(Message& m)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.Form.WmShowWindow(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
Please tell snowc how to fix this error.
Thanks.
snowc

**Comment by panthersdude2001** [comment]
Issue with Above title is getting changed in next release.
Will remain open for the time being.

**Comment by panthersdude2001** [comment]
Next release will fix this bug.

**Comment by panthersdude2001** [comment]
Closing as 1315 has been released.
