### ISSUE TITLE
snowc has a problem - The error was: Click to see exception details.

### ISSUE THREAD

**Issue by panthersdude2001** [panthersdude2001/UTimer#8]
The user snowc on computer BRYCE-PC, has encountered an error when using the program. The following details follows.
System.ArgumentNullException: Argument cannot be Nothing.
Parameter name: location
   at Microsoft.VisualBasic.Devices.Audio.ValidateFilename(String location)
   at Microsoft.VisualBasic.Devices.Audio.Play(String location, AudioPlayMode playMode)
   at WCT_Timer.Settings.MWPlayButtonS_Click(Object sender, EventArgs e) in C:\Users\snowc\Source\Repos\WCT-Timer\WDLCT 3.5\Wildcat All-In-One Timer\Settings.vb:line 203
   at System.Windows.Forms.Control.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnMouseUp(MouseEventArgs mevent)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ButtonBase.WndProc(Message& m)
   at System.Windows.Forms.Button.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
Please tell snowc how to fix this error.
Thanks.
snowc

**Comment by panthersdude2001** [comment]
Problem with sound file is causing snowc (me) to crash the whole entire program. Will be fixed in 1315, where the ofd will show instead of clicking play.

**Comment by panthersdude2001** [comment]
#8 should be fixed. Will remain open until tomorrow.

**Comment by panthersdude2001** [comment]
#8 Is now fixed ahead of today's release. Closing
